gettext: fix for Linuxbrew
Fix the following error:
format-kde-kuit.c:43:28: fatal error: libxml/parser.h: No such file or directory

`gettext` offers vendored libxml2. Use it instead of compiling libxml2 by our own.

Closes #13827.