mongo-c-driver: Depends on openssl for Linuxbrew
Fix the errors:
/home/linuxbrew/.linuxbrew/Cellar/mongo-cxx-driver/3.1.2/lib/libmongocxx.so:
undefined reference to `mongoc_client_set_ssl_opts'
undefined reference to `mongoc_client_pool_set_ssl_opts'
collect2: error: ld returned 1 exit status