ansible: Fix test for Linux (particularly CI)
- My distro comes with `python2`, so this test doesn't fail locally.
- It does consistently fail on CI though because `python2` doesn't
  exist since the default Python switched to v3:
  ```
  Testing ansible
  Error: ansible: failed
  An exception occurred within a child process:
    TypeError: no implicit conversion of nil into String
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ansible.rb:573:in `+'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ansible.rb:573:in `block in <class:Ansible>'
  ```
- Now, we install it as a test-only dependency to make it work.