ykpers: fix build with an `if OS.mac?` condition
- I tried to install `ykman`, and installing its dependency `ykpers`
  failed with the error:
  ```
  ykcore_osx.c:36:32: fatal error: IOKit/hid/IOHIDLib.h: No such file or directory
  compilation terminated.
  Makefile:461: recipe for target 'ykcore_osx.lo' failed
  make[1]: *** [ykcore_osx.lo] Error 1
  ```
- The [ykpers configure
  script](https://github.com/Yubico/yubikey-personalization/blob/master/configure.ac#L71)
  states that possible values for the `--with-backend` option on
  `./configure` are "windows", "osx", "libusb" and "libusb-1.0".
- I set this to `libusb-1.0` because it's the value that fixes the
  problem for me. Worth testing on some other setups, probably!